name: Call other workflow

on:
  workflow_dispatch:

jobs:
  preliminary-staging:
    uses: siwonpawel/action_callable/.github/workflows/001_workflow.yaml@master
    with:
      example_input: 'Hello from first workflow!'
